import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <div className="nav-container">
    <div className="logo">
      <h1>Tanmay</h1>
       <div className="nav">
          <a href="/">Home</a>
          <a href="/about">About</a>
          <a href="/dashboard">DashBoard</a>
          <a href="/contact">Contact</a>
        </div>
    </div>
      </div>
       

        {children}

        <h1>Footer</h1>
        
        
        </body>
    </html>
  );
}
